[font]
size = 11.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[window]
dynamic_title = true
opacity = 0.9

[window.padding]
x = 10
y = 10

[general]
import = ["/home/luthfi/.config/alacritty/themes/dracula.toml"]
